### ISSUE TITLE
Error when running `build_all`

### ISSUE THREAD

**Issue by Martin36** [AI-Planning/pddl-generators#27]
I get the following error when running `build_all`:

```
Domain: crewplanning
ocamlbuild main.native
make: ocamlbuild: Command not found
make: *** [Makefile:5: main.native] Error 127
```

Is `ocamlbuild` required? If that is the case then maybe it should be added to the documentation

**Comment by jendrikseipp** [comment]
I agree. Can you add the necessary installation commands to the docs, please?

**Comment by guicho271828** [comment]
It is already in my branch, I remember fixing this.

**Comment by guicho271828** [comment]
ah, nevermind, I thought I added it to environment.yml in my branch, but I did not commit it.
