### ISSUE TITLE
Error in the blocksworld domain?

### ISSUE THREAD

**Issue by wenjunli-0** [AI-Planning/pddl-generators#30]

**Comment by wenjunli-0** [comment]
I am trying to generate pddl for the blocksworld domain. 

I input ./build_all in the command line, and here are the error information. 

Domain: blocksworld
make -C bwstates.1
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/bwstates.1'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/bwstates.1'
make -C 3ops/2pddl
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/3ops/2pddl'
gcc -o 2pddl 2pddl.o -O6 -Wall -g -ansi    -lm
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/3ops/2pddl'
make -C 4ops/2pddl
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/4ops/2pddl'
gcc -o 2pddl 2pddl.o -O6 -Wall -g -ansi    -lm
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/4ops/2pddl'
make -C matching
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/matching'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/matching'

**Comment by wenjunli-0** [comment]
> What happens when you run the following in the blocksworld directory?
> 
> ```shell
> make clean
> make all
> ```

$ make clean: 
cd bwstates.1 && make clean
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/bwstates.1'
rm -f *.o core *.o bwstates README
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/bwstates.1'
cd 3ops/2pddl && make clean
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/3ops/2pddl'
rm -f *.o *.bak *~ *% core *_pure_p9_c0_400.o.warnings \
        \#*\#  
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/3ops/2pddl'
cd 4ops/2pddl && make clean
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/4ops/2pddl'
rm -f *.o *.bak *~ *% core *_pure_p9_c0_400.o.warnings \
        \#*\#  
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/4ops/2pddl'
cd matching && make clean
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/matching'
rm -f 2pddl-typed 2pddl-untyped
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/matching'

$ make all 
make -C bwstates.1
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/bwstates.1'
gcc -O2  -DSZ=200   -c -o bwstates.o bwstates.c
gcc -O2  -DSZ=200 bwstates.o -o bwstates -lm
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/bwstates.1'
make -C 3ops/2pddl
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/3ops/2pddl'
gcc -c -O6 -Wall -g -ansi    2pddl.c
2pddl.c: In function ‘main’:
2pddl.c:76:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   76 |     fscanf( data, " %d", &(initial[i + 1]) );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2pddl.c:81:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   81 |     fscanf( data, " %d", &(goal[i + 1]) );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -o 2pddl 2pddl.o -O6 -Wall -g -ansi    -lm
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/3ops/2pddl'
make -C 4ops/2pddl
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/4ops/2pddl'
gcc -c -O6 -Wall -g -ansi    2pddl.c
2pddl.c: In function ‘main’:
2pddl.c:76:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   76 |     fscanf( data, " %d", &(initial[i + 1]) );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2pddl.c:81:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   81 |     fscanf( data, " %d", &(goal[i + 1]) );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -o 2pddl 2pddl.o -O6 -Wall -g -ansi    -lm
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/4ops/2pddl'
make -C matching
make[1]: Entering directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/matching'
cc 2pddl-typed.c -o 2pddl-typed
cc 2pddl-untyped.c -o 2pddl-untyped
make[1]: Leaving directory '/home/wenjun/LLMs/2024PlanBench/pddl_generators_main/blocksworld/matching'

**Comment by haz** [comment]
Kinda looks like it worked to me. Are the compiled files not there now for you to run?

**Comment by wenjunli-0** [comment]
> Kinda looks like it worked to me. Are the compiled files not there now for you to run?

I have the following filed in the directory.
$ ls
3ops  4ops  blocksworld  bwstates.1  domain.pddl  Makefile  matching  README

what command should run in the blocksworld direction? For example, I want to generate 10 pddl under 4ops?

**Comment by wenjunli-0** [comment]
> I'd probably suggest giving the README instructions a try...
> 
> https://github.com/AI-Planning/pddl-generators/blob/main/blocksworld/README#L7

well, can you give me an example? I raised this issue because I read the README and still don't know how to do it. I am not good at linux.

when I put `$ ./blocksworld 4 10`, it returns "-bash: ./blocksworld: Is a directory". 
$ ./blocksworld <ops> <num>
-bash: ./blocksworld: Is a directory

**Comment by wenjunli-0** [comment]
> I'd probably suggest giving the README instructions a try...
> 
> https://github.com/AI-Planning/pddl-generators/blob/main/blocksworld/README#L7

What if I want to generate multiple pddl at once and store them? e.g., 100 pddl examples. With the command `$ ./blocksworld 4 4`, I can only generate one pddl example at once.

**Comment by haz** [comment]
You would need to write a bash script to run it 100 times. Or a python script. Or any other script that lets you run commands in series.
